### PR TITLE
Added scopes

### PR DESCRIPTION
**Pull request by Recouse**
Added scopes support to get inforamation about user.
For example:

```
https://ipboard/applications/oauth2server/interface/me.php?access_token=...&scope=user+email
```

In plans to add access to get information from other IPS applications.

### CODE REVIEW

**Comment by wohali** [comment]
I'm afraid I am not going to accept this PR in its current form for three reasons:
1. Please remove the whitespace changes and submit those as a separate PR.
2. When submitting a PR please squash all checkins down to a single commit.
3. In the current scenario, you will break rocket.chat support as their OAuth integration expects an email and does not know to ask for a scope. Since I built this integration specifically to support Rocket.Chat unless profile email is returned by default this PR is rejected.

Please reconsider.

**Comment by wohali** [comment]
FYI, I wouldn't be averse to adding scope selection in the _ACP_ setup for a given integration. We could have a multiselect that allowed the IPS4 Admin to select which fields were exposed for a given integration. I think this would provide better control than expecting the OAuth client/consumer to specify scopes at request time. What do you think?

**Comment by Recouse** [comment]
@wohali yeah, it will be better.

**Comment by wohali** [comment]
Hey @Recouse I'm about to commit my changes for scope support along with support for a default scope if one is not specified. Hopefully v1.2.0 (the release with this support) does what you need - I separated the `user.email` scope from the `user.profile` one. If not please submit a new PR and I'll be glad to review.

**Pull request closed without merging**
